CREATE DATABASE QUIZ_ADS;
USE QUIZ_ADS;

CREATE TABLE USUARIOS (
	ID INT AUTO_INCREMENT,
    NOME NVARCHAR(200) NOT NULL,
    EMAIL NVARCHAR(200) NOT NULL,
    SENHA NVARCHAR(200) NOT NULL,
    TIPO CHAR(1) NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE USUARIOS ADD CONSTRAINT UQ_EMAIL UNIQUE (EMAIL);

CREATE TABLE PERGUNTAS (
	ID INT AUTO_INCREMENT,
    TEXTO TEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PERGUNTAOPCOES (
	ID INT AUTO_INCREMENT,
    IDPERGUNTA INT NOT NULL,
    TEXTO TEXT NOT NULL,
    CORRETA CHAR(1) NOT NULL,
	IDENTIFICADOR CHAR(1) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (IDPERGUNTA) REFERENCES PERGUNTAS (ID)
);

CREATE TABLE USUARIOPONTUACOES (
	ID INT AUTO_INCREMENT,
    IDUSUARIO INT NOT NULL,
    QTDACERTOS INT NOT NULL,
    QTDQUESTOES INT NOT NULL,
    PERCENTUAL DOUBLE NOT NULL,
    DATA DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS (ID)
);